from __future__ import annotations

import json
import os
from pathlib import Path

from .markdown import escape_title, fenced, render_module


STYLE = Path(__file__).resolve().parent.parent / "styles" / "book.typ"


def typ(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "(" + ", ".join(typ(v) for v in value) + ",)"
    if isinstance(value, dict):
        return "(" + ", ".join(k.replace("_", "-") + ": " + typ(v) for k, v in value.items()) + ",)"
    return str(value)


def relative(path: Path, base: Path):
    return os.path.relpath(path, base).replace(os.sep, "/")


def render(project):
    config = project.config
    md = ["<!-- Generated by build.py; edit templates/ or templates.toml. -->\n", "# " + escape_title(config["book"]["title"]) + "\n"]
    # A generated local copy keeps the output style relative to its entrypoint.
    ts = ['// Generated by build.py; edit source modules / templates.toml / styles/book.typ.', '#import ".templatebook-style.typ": book',
          '#show: book.with(config: ' + typ({"book": config["book"], "layout": config["layout"], "module_count": len(project.modules), "topic_count": len(project.entries)}) + ", cover: " +
          (f'image({typ(relative(project.root / config["cover"]["image"], project.output))}, width: 100%, height: 92mm, fit: "cover")' if config["cover"]["image"] else "none") + ")"]
    has_markdown = any(e.language == "markdown" for e in project.modules)
    if has_markdown:
        ts += ['#import "@preview/cmarker:0.1.10"', '#import "@preview/mitex:0.2.7": mitex']
    for entry in project.walk():
        md += [f'<a id="{entry.anchor}"></a>\n', "#" * min(entry.level + 1, 6) + " " + escape_title(entry.title) + "\n"]
        ts += [f'\n// source: {entry.key}', f'#heading(level: {entry.level}, {typ(entry.title)}) <{entry.anchor}>']
        if entry.directory:
            continue
        source = relative(entry.path, project.output)
        if entry.language == "markdown":
            md += [render_module(entry, project)]
            base = relative(entry.path.parent, project.output)
            ts += ['#[', '  #set heading(outlined: false, numbering: none)',
                   '  #cmarker.render(', f'    read({typ(source)}),',
                   f'    h1-level: {entry.level + 1},', '    set-document-title: false, raw-typst: false, smart-punctuation: false,',
                   f'    label-prefix: {typ(entry.anchor + "-")},', '    math: mitex,',
                   '    scope: (image: (path, ..args) => {',
                   f'      let resolved = if path.starts-with("/") {{ path }} else {{ {typ(base + "/")} + path }}',
                   '      image(resolved, width: 100%, ..args)', '    }),', '  )', ']']
        else:
            md += [fenced(entry.text, entry.language if entry.language != "typst" else "typst")]
            if entry.language == "typst":
                ts += ['#[', f'  #set heading(offset: {entry.level}, outlined: false, numbering: none)', f'  #include {typ(source)}', ']']
            else:
                ts += [f'#raw(read({typ(source)}), block: true, lang: {typ(entry.language)})']
    return "\n".join(md).rstrip() + "\n", "\n".join(ts).rstrip() + "\n"


def write_if_changed(path, value):
    data = value.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(data)
    temporary.replace(path)


def build(project):
    # Render and validate all modules before touching the previous successful outputs.
    md, ts = render(project)
    project.output.mkdir(parents=True, exist_ok=True)
    style = STYLE.read_text(encoding="utf-8")
    write_if_changed(project.output / ".templatebook-style.typ", style)
    write_if_changed(project.output / ".templatebook-code.tmTheme", (STYLE.parent / "code.tmTheme").read_text(encoding="utf-8"))
    write_if_changed(project.output / "templates.md", md)
    write_if_changed(project.output / "templates.typ", ts)
